version: '3.1'

services:
  php:
    # image: php:7.4-apache
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    restart: always
  mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080